version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: tasks
    ports:
      - "27017:27017"
  mongo-backend:
    build:
      context: ./mongo-backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./mongo-backend:/app/
    links:
      - mongodb
    depends_on: 
      - mongodb
  frontend:
    build: ./frontend
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - PORT=80
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - sql-backend
